name: Run a Python script
description: Empty Github Action template running a simple Python script
inputs:
  folder_path:
    description: Path to folders containing pdf files organised by author
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: JoshWilde/test-python-action
    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Glob Folders
      uses: tj-actions/glob@v7.14
      id: glob_folders
      with:
        files: |
          */*
          
    - name: Glob PDFs
      uses: tj-actions/glob@v7.14
      id: glob_PDFs
      with:
        files: |
          */*/*.pdf
    
    - name: Run Python script
      shell: bash
      env:
        FOLDER_PATH: ${{ inputs.folder_path }}
        GLOB_FOLDERS: ${{ steps.glob_folders.outputs.paths }}
        GLOB_PDFS: ${{ steps.glob_PDFs.outputs.paths }}
      run: |
        pip install -r requirements.txt
        python Author_Papers.py
    - name: Push File to repo
      rerun: |
        git config --global user.name "JoshWilde"
        git config --global user.email "jww258@open.ac.uk"
        
        git add Author_Dict_generated.npy
        git commit -m "Added Author Dictionary"
        git push
