name: Run a Python script
description: Empty Github Action template running a simple Python script
inputs:
  folder_path:
    description: Path to folders containing pdf files organised by author
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: JoshWilde/test-python-action
    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Run Python script
      shell: bash
      env:
        FOLDER_PATH: ${{ inputs.folder_path }}
      run: |
        pip install -r requirements.txt
        python Author_Papers.py
