name: Author Vector Generation
on:
  workflow_dispatch:
    inputs:
      folder_location:
        description: 'Location of folders containing PDFs for each author'
        required: true
      #branch:
      #  description: 'Git branch where the paper Markdown file is'
      #  required: false
      #issue_id:
      #  description: 'The issue number of the submission'
      #  required: true
jobs:
  reviewer-matching:
    name: Author Vector Generation
    runs-on: ubuntu-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      #- name: Generate PDF
      #  id: generate-files
      #  uses: xuanxu/paper-action@main
      #  with:
      #    repository_url: ${{ github.event.inputs.repository_url }}
      #    branch: ${{ github.event.inputs.branch }}
      #    issue_id: ${{ github.event.inputs.issue_id }}
      #    journal: test_journal
      - name: Test Python
        uses: JoshWilde/test-python-action/act_authors@main
        with:
          folder_path: ${{ github.event.inputs.folder_location }} #${{ steps.generate-files.outputs.pdf_path}} #${{ github.event.inputs.repository_url }}
