name: Reviewers matching
on:
  workflow_dispatch:
    inputs:
      repository_url:
        description: 'URL of the repository containing the paper file'
        required: true
      #branch:
      #  description: 'Git branch where the paper Markdown file is'
      #  required: false
      #issue_id:
      #  description: 'The issue number of the submission'
      #  required: true
jobs:
  reviewer-matching:
    name: Reviewer matching
    runs-on: ubuntu-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      #- name: Generate PDF
      #  id: generate-files
      #  uses: xuanxu/paper-action@main
      #  with:
      #    repository_url: ${{ github.event.inputs.repository_url }}
      #    branch: ${{ github.event.inputs.branch }}
      #    issue_id: ${{ github.event.inputs.issue_id }}
      #    journal: test_journal
      - name: Check out repo
        uses: actions/checkout@v3
          with: JoshWilde/test-python-action
          ref: v1.0
          token: token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./.github/JoshWilde/test-python-action
          
      - name: Test Python
        #uses: ./.github/JoshWilde/test-python-action/action #@main
        uses: ./.github/JoshWilde/test-python-action/action #JoshWilde/test-python-action@main
        with:
          paper_path: ${{ github.event.inputs.repository_url }} #${{ steps.generate-files.outputs.pdf_path}} #${{ github.event.inputs.repository_url }}
